//
//  DataManager.swift
//  TestLocationService
//
//  Created by Alex Odintsov on 25.06.2018.
//  Copyright © 2018 Alex Odintsov. All rights reserved.
//

import Foundation

class DataManager {
    
    static let sharedInstance = DataManager()
                                //10 meters
    var settings: [Preset] = [Preset(accuracyname: "лучшая",
                                     distancename: "10 метров",
                                     accuracy: .best,
                                     distance: .tenMeters,
                                     isActive: true),
                              Preset(accuracyname: "для навигации",
                                     distancename: "10 метров",
                                     accuracy: .hundredMeters,
                                     distance: .tenMeters,
                                     isActive: false),
                              Preset(accuracyname: "около 10 метров",
                                     distancename: "10 метров",
                                     accuracy: .nearestTenMeters,
                                     distance: .tenMeters,
                                     isActive: false),
                              Preset(accuracyname: "100 метров",
                                     distancename: "10 метров",
                                     accuracy: .hundredMeters,
                                     distance: .tenMeters,
                                     isActive: false),
                              Preset(accuracyname: "1 киллометр",
                                     distancename: "10 метров",
                                     accuracy: .killometer,
                                     distance: .tenMeters,
                                     isActive: false),
                              Preset(accuracyname: "3 киллометра",
                                     distancename: "10 метров",
                                     accuracy: .threeKillometers,
                                     distance: .tenMeters,
                                     isActive: false),
                              //100 meters
                              Preset(accuracyname: "лучшая",
                                     distancename: "100 метров",
                                     accuracy: .best,
                                     distance: .hundredMeters,
                                     isActive: false),
                              Preset(accuracyname: "для навигации",
                                     distancename: "100 метров",
                                     accuracy: .bestForNavigation,
                                     distance: .hundredMeters,
                                     isActive: false),
                              Preset(accuracyname: "около 10 метров",
                                     distancename: "100 метров",
                                     accuracy: .nearestTenMeters,
                                     distance: .hundredMeters,
                                     isActive: false),
                              Preset(accuracyname: "100 метров",
                                     distancename: "100 метров",
                                     accuracy: .hundredMeters,
                                     distance: .hundredMeters,
                                     isActive: false),
                              Preset(accuracyname: "1 киллометр",
                                     distancename: "100 метров",
                                     accuracy: .killometer,
                                     distance: .hundredMeters,
                                     isActive: false),
                              Preset(accuracyname: "3 киллометра",
                                     distancename: "100 метров",
                                     accuracy: .threeKillometers,
                                     distance: .hundredMeters,
                                     isActive: false),
                              //500 meters
                              Preset(accuracyname: "лучшая",
                                     distancename: "500 метров",
                                     accuracy: .best,
                                     distance: .fiveHundredMeters,
                                     isActive: false),
                              Preset(accuracyname: "для навигации",
                                     distancename: "50 метров",
                                     accuracy: .bestForNavigation,
                                     distance: .fiveHundredMeters,
                                     isActive: false),
                              Preset(accuracyname: "около 10 метров",
                                     distancename: "500 метров",
                                     accuracy: .nearestTenMeters,
                                     distance: .fiveHundredMeters,
                                     isActive: false),
                              Preset(accuracyname: "100 метров",
                                     distancename: "500 метров",
                                     accuracy: .hundredMeters,
                                     distance: .fiveHundredMeters,
                                     isActive: false),
                              Preset(accuracyname: "1 киллометр",
                                     distancename: "500 метров",
                                     accuracy: .killometer,
                                     distance: .fiveHundredMeters,
                                     isActive: false),
                              Preset(accuracyname: "3 киллометра",
                                     distancename: "500 метров",
                                     accuracy: .threeKillometers,
                                     distance: .fiveHundredMeters,
                                     isActive: false),
                              //1000 meters
                              Preset(accuracyname: "лучшая",
                                     distancename: "1000 метров",
                                     accuracy: .best,
                                     distance: .killometer,
                                     isActive: false),
                              Preset(accuracyname: "для навигации",
                                     distancename: "1000 метров",
                                     accuracy: .bestForNavigation,
                                     distance: .killometer,
                                     isActive: false),
                              Preset(accuracyname: "около 10 метров",
                                     distancename: "1000 метров",
                                     accuracy: .nearestTenMeters,
                                     distance: .killometer,
                                     isActive: false),
                              Preset(accuracyname: "100 метров",
                                     distancename: "1000 метров",
                                     accuracy: .hundredMeters,
                                     distance: .killometer,
                                     isActive: false),
                              Preset(accuracyname: "1 киллометр",
                                     distancename: "1000 метров",
                                     accuracy: .killometer,
                                     distance: .killometer,
                                     isActive: false),
                              Preset(accuracyname: "3 киллометра",
                                     distancename: "1000 метров",
                                     accuracy: .threeKillometers,
                                     distance: .killometer,
                                     isActive: false)]
    
    func fetchSettings() -> [Preset] {
        return settings
    }
}
